package org.zotero.android.architecture

/**
 * Represents a change to a View.
 * Can either be [ViewState], [ViewEvent], or [ViewEffect].
 */
interface ViewChange {
    /** Cleans up verbose toString() implementations.*/
    fun sanitizedToString(): String {
        val rawString = this.toString()
        return rawString
    }
}

/**
 * The current state of the view. Indicates whether loading, or can retry, etc.
 * This should generally be implemented by a Data Class.
 */
interface ViewState : ViewChange

/**
 * A user submitted event generated by the view. Should either be a Kotlin
 * Object or a Data Class.
 */
@Deprecated("No longer needed in ViewModel2")
interface ViewEvent : ViewChange

/**
 * Represents transient effects that the view should do only once, such as
 * showing an error message, navigating to a different screen, or showing a
 * dialog. Should either be a Kotlin Object or a Data Class.
 */
interface ViewEffect : ViewChange
